### ISSUE TITLE
print shows that X axis not perpendicular to y axis. 88 degrees instead of 90

### ISSUE THREAD

**Issue by dokk179** [ZONESTAR3D/Z9#4]
In the Zonestar Z9V5  I noticed that printing a simple square gives me a Trapezoid (distortions of exactly 2 degrees along the y axis.) 
To confirm it I designed a Trapezoid where the y axis line is 2 degrees off and it printed me a perfect square.
I wonder if there is a way to resolve this problem

**Comment by ZONESTAR3D** [comment]
The difference in length and tightness between the two belts may cause this issue. You can correct it by following these steps:
Loosen the belt>>Move the X pulley to the rear (easier to handle)>>Adjust and tighten the belt
